modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="paintable"
version="1.5a-1.20.1"
displayName="Paintable"
logoFile="paintable_logo.png"
authors="Im_Maker"
credits=""
description='''
Adds Paint Brushes to paint blocks like Planks, Bricks and Mud Bricks!
Twitter/X:I_AmMaker
'''
[[dependencies.paintable]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.paintable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.2)"
    ordering="NONE"
    side="BOTH"